services:

  client:
    image: nicolaka/netshoot
    container_name: client
    command: sh -c "ip addr flush dev eth0 && sleep infinity"
    cap_add:
      - NET_ADMIN
    networks:
      netA:

  routeur:
    image: nicolaka/netshoot
    container_name: routeur
    command: sh -c "sysctl -w net.ipv4.ip_forward=1 && sleep infinity"
    cap_add:
      - NET_ADMIN
    networks:
      netA:
        ipv4_address: 10.10.0.254
      netB:
        ipv4_address: 10.20.0.254

  serveur1:
    image: python:3.9-slim
    container_name: serveur1
    command: sh -c "apt update && apt install -y iproute2 iputils-ping net-tools curl tcpdump && python3 -m http.server 8000"
    networks:
      netB:
        ipv4_address: 10.20.0.10

  dns1:
    image: debian:stable-slim
    container_name: dns1
    command: sh -c "apt update && apt install -y dnsmasq tcpdump iproute2 && dnsmasq -k"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dns1/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      netB:
        ipv4_address: 10.20.0.53

  dns2:
    image: debian:stable-slim
    container_name: dns2
    command: sh -c "apt update && apt install -y dnsmasq tcpdump iproute2 && dnsmasq -k"
    volumes:
      - ./dns2/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      netB:
        ipv4_address: 10.20.0.54

networks:
  netA:
    ipam:
      config:
        - subnet: 10.10.0.0/24
  netB:
    ipam:
      config:
        - subnet: 10.20.0.0/24
